services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: student
      POSTGRES_USER: skd
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

#  docker-demo:
#    container_name: docker-demo-app
#    image: docker-demo-image
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    networks:
#      - docker-ntw
#    restart: unless-stopped

networks:
  postgres:
    #  docker-ntw:
    driver: bridge

volumes:
  postgres:
  pgadmin: